name: foodcourtapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at

# geofence_service: ^3.4.8
# fl_location: ^1.2.1
# flutter_foreground_task: ^3.5.5
# flutter_activity_recognition: ^1.2.1

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  http: ^0.13.3
  intl: ^0.17.0
  iconly: 1.0.0
  provider: ^5.0.0
  package_info: ^2.0.2
  device_info: ^2.0.3
  shared_preferences: ^2.0.5
  rxdart: 0.27.2
  firebase_auth: ^3.1.0
  flutter_svg: 1.0.0
  firebase_core: ^1.7.0
  firebase_database: ^9.0.0
  firebase_analytics: ^8.3.4
  cloud_firestore: ^3.1.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: 2.0.8
  google_maps_webservice: 0.0.16
  animated_text_kit: 1.3.1
  geolocator: ^8.0.1
  geocoding: ^2.0.1
  get: 4.5.1
  google_sign_in: ^5.0.3
  animate_do: ^2.0.0
  flutter_lock_screen: ^2.0.1
  local_auth: ^1.1.6
  permission_handler: ^8.1.0
  dio: ^4.0.4
  location: ^4.3.0
  maps_launcher: ^2.0.1
  image_picker: ^0.8.5+3
  dots_indicator: ^2.1.0
  get_storage: ^2.0.3
  getwidget: ^3.0.1
  cached_network_image: ^3.2.1
  flutterfire_ui: ^0.3.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  geocode: ^1.0.1
  geocoder2: ^1.1.2
  cupertino_icons: 1.0.4
  sqflite: ^2.0.2
  path_provider: ^2.0.4
  flutter_lints: ^1.0.0




  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # Illustration by <a href="https://icons8.com/illustrations/author/zD2oqC8lLBBA">Icons 8</a> from <a href="https://icons8.com/illustrations">Ouch!</a>

  assets:
    - lib/pict/burg.svg
    - lib/pict/fried-rice-2.svg
    - lib/pict/kentang.svg
    - lib/pict/ilustrasi-soft-drink-ilustrasi-minuman-ringan-ilustrasi-minuman-bersoda_20180719_084159.svg
    - lib/pict/burg.jpg
    - lib/pict/fried-rice-2.jpg
    - lib/pict/kentang.jpg
    - lib/pict/softdrink.jpg
    - lib/pict/hijau.jpg
    - lib/pict/nusa.jpg
    - lib/pict/taro.jpg
    - lib/pict/thai.jpg
    - lib/pict/ob1.png
    - lib/pict/ob2.png
    - lib/pict/ob3.png
    - lib/pict/ob4.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
